name: deploydist

# on: [push] 
on:
    push:
        branches:
            - main
        paths-ignore:
            - '.github/workflows/*'
            - README.md

jobs:
  hello_world_job: # Define a job named 'hello_world_job'
    runs-on: ubuntu-latest # Specify the runner environment
    steps:
      - name: 'Get Code'
        uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v4
        with: 
           node-version: 20

      - name: Cache Dependencies
        uses: actions/cache@v4
        with: 
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}

      - name: 'install dependecies'
        run: npm install
      - name: 'Run Tests'
        run: npm run test
        
  deploy: 
    needs: hello_world_job
    runs-on: ubuntu-latest 
    steps:
      - name: 'Get Code'
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with: 
           node-version: 20
    
      - name: Cache Dependencies
        uses: actions/cache@v4
        with: 
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}


      - name: 'install dependecies'
        run: npm install
        
      - name: 'create build'
        run: npm run build
      

           